python src/train_me.py \
    --train_file train.json \
    --dev_file dev.json \
    --test_file test.json \
    --model_name_or_path /data/pretrained/BiomedNLP-PubMedBERT-base-uncased-abstract \
    --num_epoch 50 \
    --learning_rate 5e-5 \
    --save_path ./model/BioRED-me.pt \
    --notes BioRED-me  \
    --dataset BioRED \
    --no_dev 1
